# Generated by Django 5.2.4 on 2025-08-06 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='allergy_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عناصر الحساسية'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.menu'),
        ),
        migrations.AlterField(
            model_name='section',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to=settings.AUTH_USER_MODEL),
        ),
    ]
