# Generated by Django 5.2.4 on 2025-08-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_restaurantprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True),
        ),
    ]
