# Generated by Django 5.2.4 on 2025-08-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_menu_is_published_menu_public_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='default_language',
            field=models.CharField(blank=True, default='ar', max_length=5),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
