# Generated by Django 5.2.4 on 2025-08-16 09:21

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_restaurantprofile_default_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDisplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('hours', models.CharField(blank=True, default='', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.models.menu_logo_upload_path)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=core.models.menu_hero_upload_path)),
                ('theme', models.CharField(blank=True, default='default', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_settings', to='core.menu')),
            ],
            options={
                'verbose_name': 'Menu Display Settings',
                'verbose_name_plural': 'Menu Display Settings',
                'constraints': [models.UniqueConstraint(fields=('menu',), name='unique_display_settings_per_menu')],
            },
        ),
    ]
