# Generated by Django 5.2.4 on 2025-08-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_dish_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantProfile',
        ),
    ]
