# Generated by Django 5.2.4 on 2025-08-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_dish_price_dishprice'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dishprice',
            index=models.Index(fields=['dish', 'sort_order'], name='core_dishpr_dish_id_e9034f_idx'),
        ),
        migrations.AddIndex(
            model_name='dishprice',
            index=models.Index(fields=['dish', 'is_default'], name='core_dishpr_dish_id_7b51f0_idx'),
        ),
    ]
