# Generated by Django 5.2.4 on 2025-08-31 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_allergen_dish_codes_updated_at_dish_extra_additives_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='de', help_text='لغة المصطلحات المقترَحة (افتراضيًا: الألمانية).', max_length=8)),
                ('text_snapshot', models.TextField(help_text='نص المصدر ساعة توليد الاقتراح (name + description بعد التنظيف).')),
                ('candidates', models.JSONField(blank=True, default=list, help_text='قائمة مصطلحات مع درجات الثقة وربط اختياري بـ Ingredient.')),
                ('model_name', models.CharField(blank=True, default='', help_text='اسم نموذج الـLLM المستخدم.', max_length=100)),
                ('prompt_hash', models.CharField(blank=True, help_text='هاش للمحفّز لتجنّب الازدواجية.', max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='pending', max_length=16)),
                ('notes', models.TextField(blank=True, default='', help_text='ملاحظات أثناء المراجعة/التطبيق.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_suggestions', to='core.dish')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dish'], name='core_ingred_dish_id_3cc8d0_idx'), models.Index(fields=['status'], name='core_ingred_status_48f5cf_idx'), models.Index(fields=['lang'], name='core_ingred_lang_d9bde8_idx'), models.Index(fields=['created_at'], name='core_ingred_created_740034_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('prompt_hash__isnull', False)), fields=('dish', 'prompt_hash', 'model_name', 'lang'), name='uniq_suggestion_per_prompt')],
            },
        ),
    ]
