# Generated by Django 5.2.4 on 2025-08-31 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ingredientsuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordLexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='de', help_text='رمز اللغة (مثل de, ar, en).', max_length=8)),
                ('term', models.CharField(help_text='الكلمة/العبارة كما يُدخلها المستخدم (قد تحتوي أحرف كبيرة/لكنة/مسافات).', max_length=160)),
                ('normalized_term', models.CharField(db_index=True, editable=False, help_text='نسخة مطبّعة من term لتسريع المطابقة البسيطة.', max_length=160)),
                ('is_regex', models.BooleanField(default=False, help_text='إذا true تُفسَّر term كتعبيـر نمطي (Regex).')),
                ('weight', models.FloatField(default=1.0, help_text='وزن/أولوية عند تراكب النتائج (افتراضي: 1.0).')),
                ('is_active', models.BooleanField(default=True, help_text='تفعيل/تعطيل السطر.')),
                ('notes', models.TextField(blank=True, default='', help_text='ملاحظات داخلية.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergens', models.ManyToManyField(blank=True, help_text='حساسيّات مرتبطة مباشرةً بهذه الكلمة (اختياري).', related_name='lexeme_triggers', to='core.allergen')),
                ('ingredient', models.ForeignKey(blank=True, help_text='Ingredient مرتبط بهذه الكلمة المفتاحية (اختياري).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lexemes', to='core.ingredient')),
                ('owner', models.ForeignKey(blank=True, help_text='اختياري: لتخصيص القاموس لمالك معيّن. إذا تُرك فارغًا فهو عام.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lexemes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Keyword Lexeme',
                'verbose_name_plural': 'Keyword Lexemes',
                'ordering': ['lang', 'normalized_term', 'id'],
                'indexes': [models.Index(fields=['lang', 'is_active'], name='core_keywor_lang_d7f158_idx'), models.Index(fields=['owner', 'lang'], name='core_keywor_owner_i_4aed12_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'lang', 'term', 'is_regex'), name='uniq_lexeme_owner_lang_term_regex')],
            },
        ),
        migrations.CreateModel(
            name='NegationCue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='de', help_text='رمز اللغة (مثل de, ar, en).', max_length=8)),
                ('cue', models.CharField(help_text='العبارة/الكلمة التي تدل على النفي (مثلاً ohne/بدون/without).', max_length=100)),
                ('normalized_cue', models.CharField(db_index=True, editable=False, help_text='نسخة مطبّعة من cue.', max_length=100)),
                ('is_regex', models.BooleanField(default=False, help_text='إذا true تُفسَّر cue كتعبيـر نمطي (Regex).')),
                ('window_before', models.PositiveSmallIntegerField(default=3, help_text='عدد الكلمات قبل عبارة النفي التي تتأثّر بالنفي.')),
                ('window_after', models.PositiveSmallIntegerField(default=2, help_text='عدد الكلمات بعد عبارة النفي التي تتأثّر بالنفي.')),
                ('is_active', models.BooleanField(default=True, help_text='تفعيل/تعطيل سطر النفي.')),
                ('notes', models.TextField(blank=True, default='', help_text='ملاحظات داخلية.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='اختياري: نفي خاص بمالك معيّن. إذا فارغ: نفي عام.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negation_cues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Negation Cue',
                'verbose_name_plural': 'Negation Cues',
                'ordering': ['lang', 'normalized_cue', 'id'],
                'indexes': [models.Index(fields=['lang', 'is_active'], name='core_negati_lang_731fb3_idx'), models.Index(fields=['owner', 'lang'], name='core_negati_owner_i_c8812f_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'lang', 'cue', 'is_regex'), name='uniq_negcue_owner_lang_cue_regex')],
            },
        ),
    ]
