# Generated by Django 5.2.4 on 2025-09-06 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_keywordlexeme_negationcue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordlexeme',
            options={'ordering': ('owner_id', 'lang', '-priority', '-weight', 'id'), 'verbose_name': 'Keyword Lexeme', 'verbose_name_plural': 'Keyword Lexemes'},
        ),
        migrations.AlterModelOptions(
            name='negationcue',
            options={'ordering': ('owner_id', 'lang', 'normalized_cue', 'id'), 'verbose_name': 'Negation Cue', 'verbose_name_plural': 'Negation Cues'},
        ),
        migrations.RemoveConstraint(
            model_name='keywordlexeme',
            name='uniq_lexeme_owner_lang_term_regex',
        ),
        migrations.RemoveIndex(
            model_name='keywordlexeme',
            name='core_keywor_lang_d7f158_idx',
        ),
        migrations.RemoveIndex(
            model_name='negationcue',
            name='core_negati_lang_731fb3_idx',
        ),
        migrations.RenameIndex(
            model_name='keywordlexeme',
            new_name='idx_lex_owner_lang',
            old_name='core_keywor_owner_i_4aed12_idx',
        ),
        migrations.RenameIndex(
            model_name='negationcue',
            new_name='idx_neg_owner_lang',
            old_name='core_negati_owner_i_c8812f_idx',
        ),
        migrations.AddField(
            model_name='keywordlexeme',
            name='priority',
            field=models.IntegerField(default=0, help_text='أولوية اختيارية للفرز (مفيدة إن كان محرك القواعد يرتّب بـ -priority).', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='keywordlexeme',
            name='allergens',
            field=models.ManyToManyField(blank=True, help_text='حساسيّات مرتبطة مباشرةً بالمصطلح (تُستخدم لو لم يكن ingredient).', related_name='lexemes', to='core.allergen', verbose_name='Allergens'),
        ),
        migrations.AlterField(
            model_name='keywordlexeme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='keywordlexeme',
            name='ingredient',
            field=models.ForeignKey(blank=True, help_text='ربط اختياري بمكوّن معروف.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lexemes', to='core.ingredient', verbose_name='Ingredient'),
        ),
        migrations.AlterField(
            model_name='keywordlexeme',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='keywordlexeme',
            name='is_regex',
            field=models.BooleanField(default=False, help_text='إن كان المصطلح تعبيرًا نمطيًا (Regex).', verbose_name='Is regex pattern'),
        ),
        migrations.AlterField(
            model_name='keywordlexeme',
            name='lang',
            field=models.CharField(default='de', help_text='رمز اللغة القصير (مثال: de).', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='keywordlexeme',
            name='normalized_term',
            field=models.CharField(db_index=True, help_text='نسخة مطبّعة من المصطلح لأغراض المطابقة.', max_length=255, verbose_name='Normalized term'),
        ),
        migrations.AlterField(
            model_name='keywordlexeme',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='keywordlexeme',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='اختياري: مالك القاموس؛ NULL يعني قاموس عام.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lexemes', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='keywordlexeme',
            name='term',
            field=models.CharField(help_text='النص الأصلي للمصطلح.', max_length=255, verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='keywordlexeme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='keywordlexeme',
            name='weight',
            field=models.FloatField(default=1.0, help_text='وزن اختياري للفرز عند التعارض.', verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='negationcue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='negationcue',
            name='cue',
            field=models.CharField(help_text='العبارة/الكلمة التي تدل على النفي (مثلاً ohne/بدون/without).', max_length=120, verbose_name='Negation cue'),
        ),
        migrations.AlterField(
            model_name='negationcue',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='negationcue',
            name='is_regex',
            field=models.BooleanField(default=False, verbose_name='Is regex pattern'),
        ),
        migrations.AlterField(
            model_name='negationcue',
            name='lang',
            field=models.CharField(default='de', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='negationcue',
            name='normalized_cue',
            field=models.CharField(db_index=True, editable=False, max_length=120, verbose_name='Normalized cue'),
        ),
        migrations.AlterField(
            model_name='negationcue',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='negationcue',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='اختياري: نفي خاص بمالك معيّن. إذا فارغ: نفي عام.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negation_cues', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='negationcue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='negationcue',
            name='window_after',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Window after (words)'),
        ),
        migrations.AlterField(
            model_name='negationcue',
            name='window_before',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Window before (words)'),
        ),
        migrations.AddIndex(
            model_name='keywordlexeme',
            index=models.Index(fields=['lang', 'normalized_term'], name='idx_lex_lang_norm'),
        ),
        migrations.AddIndex(
            model_name='keywordlexeme',
            index=models.Index(fields=['is_active'], name='idx_lex_is_active'),
        ),
        migrations.AddIndex(
            model_name='negationcue',
            index=models.Index(fields=['lang', 'normalized_cue'], name='idx_neg_lang_norm'),
        ),
        migrations.AddIndex(
            model_name='negationcue',
            index=models.Index(fields=['is_active'], name='idx_neg_is_active'),
        ),
        migrations.AddConstraint(
            model_name='keywordlexeme',
            constraint=models.UniqueConstraint(fields=('owner', 'lang', 'normalized_term', 'is_regex'), name='uniq_lexeme_owner_lang_norm_regex'),
        ),
    ]
