# Generated by Django 5.2.4 on 2025-09-07 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_keywordlexeme_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ingredient', 'Ingredient'), ('regex', 'Regex/Lexeme'), ('llm', 'LLM'), ('trace', 'Trace/Spuren'), ('manual', 'Manual')], default='regex', max_length=12)),
                ('confidence', models.FloatField(default=0.0, help_text='0..1')),
                ('rationale', models.TextField(blank=True, default='', help_text="سبب مختصر: مثل 'Käse → G (Milch)'")),
                ('is_confirmed', models.BooleanField(default=False, help_text='اعتماد بشري نهائي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dish_rows', to='core.allergen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dish_allergens', to=settings.AUTH_USER_MODEL)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergen_rows', to='core.dish')),
            ],
            options={
                'ordering': ['dish_id', 'allergen__code'],
                'indexes': [models.Index(fields=['dish'], name='core_dishal_dish_id_9c4449_idx'), models.Index(fields=['allergen'], name='core_dishal_allerge_ce5100_idx'), models.Index(fields=['source'], name='core_dishal_source_9d629c_idx'), models.Index(fields=['is_confirmed'], name='core_dishal_is_conf_ef2c55_idx'), models.Index(fields=['created_at'], name='core_dishal_created_eb0c9c_idx')],
                'unique_together': {('dish', 'allergen')},
            },
        ),
    ]
