# Generated by Django 5.2.4 on 2025-09-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_dishallergen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordlexeme',
            name='normalized_term',
            field=models.CharField(db_index=True, help_text='نسخة مطبّعة من المصطلح لأغراض المطابقة (تُحدَّث تلقائيًا).', max_length=255, verbose_name='Normalized term'),
        ),
        migrations.AlterField(
            model_name='negationcue',
            name='normalized_cue',
            field=models.CharField(db_index=True, editable=False, help_text='نسخة مطبّعة من عبارة النفي (تُحدَّث تلقائيًا).', max_length=120, verbose_name='Normalized cue'),
        ),
        migrations.AddIndex(
            model_name='keywordlexeme',
            index=models.Index(fields=['lang', 'normalized_term', 'owner', 'is_regex'], name='idx_lex_lookup'),
        ),
    ]
