# Generated by Django 5.2.4 on 2025-09-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_keywordlexeme_normalized_term_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dishallergen',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dishallergen',
            constraint=models.UniqueConstraint(fields=('dish', 'allergen'), name='uniq_dish_allergen'),
        ),
        migrations.AddConstraint(
            model_name='dishallergen',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), name='chk_confidence_0_1'),
        ),
    ]
