# Generated by Django 5.2.4 on 2025-11-10 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_dishallergen_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additivelegend',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='additivelegend',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='additivelegend',
            name='label_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='additivelegend',
            name='label_de',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='additivelegend',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='additivelegend',
            name='number',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='additivelegend',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additive_legends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='additivelegend',
            index=models.Index(fields=['owner', 'number'], name='core_additi_owner_i_d2e6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='additivelegend',
            index=models.Index(fields=['number'], name='core_additi_number_5f9a03_idx'),
        ),
        migrations.AddConstraint(
            model_name='additivelegend',
            constraint=models.UniqueConstraint(fields=('owner', 'number'), name='uniq_owner_number'),
        ),
        migrations.AddConstraint(
            model_name='additivelegend',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('number',), name='uniq_global_number_when_owner_null'),
        ),
    ]
