# Generated by Django 5.2.4 on 2025-11-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_whatsapp_hero_crop_to_menudisplaysettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='section',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
