# Generated by Django 5.2.4 on 2025-11-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_section_options_section_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='dish',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
