# Generated by Django 5.2.4 on 2025-11-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_dish_options_dish_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudisplaysettings',
            name='show_images',
            field=models.BooleanField(default=True),
        ),
    ]
