# Generated by Django 5.2.4 on 2025-11-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_menudisplaysettings_show_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudisplaysettings',
            name='theme',
            field=models.TextField(blank=True, default='default'),
        ),
    ]
