# Generated by Django 5.2.4 on 2025-11-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_change_theme_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Mark as favorite/recommended dish'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['is_favorite'], name='core_dish_is_favo_20ef75_idx'),
        ),
    ]
