# Generated by Django 4.2 on 2025-11-29 19:40

from django.db import migrations


def migrate_allergen_codes_forward(apps, schema_editor):
    """
    Migrate data from allergens.AllergenCode to core.Allergen.
    
    This migration:
    - Copies all AllergenCode entries to Allergen if they don't already exist
    - Updates existing Allergen entries if they're missing German labels
    - Does NOT delete AllergenCode table (kept for backward compatibility)
    """
    AllergenCode = apps.get_model('allergens', 'AllergenCode')
    Allergen = apps.get_model('core', 'Allergen')
    
    migrated_count = 0
    updated_count = 0
    skipped_count = 0
    
    for ac in AllergenCode.objects.all():
        # Try to get existing allergen by code
        try:
            allergen = Allergen.objects.get(code=ac.code)
            # Update if missing German label
            if not allergen.label_de and ac.name_de:
                allergen.label_de = ac.name_de
                if ac.name_en and not allergen.label_en:
                    allergen.label_en = ac.name_en
                if ac.name_ar and not allergen.label_ar:
                    allergen.label_ar = ac.name_ar
                allergen.save()
                updated_count += 1
            else:
                skipped_count += 1
        except Allergen.DoesNotExist:
            # Create new allergen
            Allergen.objects.create(
                code=ac.code,
                label_de=ac.name_de or '',
                label_en=ac.name_en or '',
                label_ar=ac.name_ar or '',
            )
            migrated_count += 1
    
    if migrated_count or updated_count:
        print(f"AllergenCode → Allergen migration complete:")
        print(f"  - Created: {migrated_count}")
        print(f"  - Updated: {updated_count}")
        print(f"  - Skipped: {skipped_count}")


def migrate_allergen_codes_backward(apps, schema_editor):
    """
    Reverse migration: copy Allergen back to AllergenCode.
    Note: This is a conservative reverse - we don't delete Allergen entries.
    """
    Allergen = apps.get_model('core', 'Allergen')
    AllergenCode = apps.get_model('allergens', 'AllergenCode')
    
    for allergen in Allergen.objects.all():
        AllergenCode.objects.update_or_create(
            code=allergen.code,
            defaults={
                'name_de': allergen.label_de or '',
                'name_en': allergen.label_en or '',
                'name_ar': allergen.label_ar or '',
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_dish_is_favorite_dish_core_dish_is_favo_20ef75_idx'),
        ('allergens', '0001_initial'),  # Ensure allergens app exists
    ]

    operations = [
        migrations.RunPython(
            migrate_allergen_codes_forward,
            reverse_code=migrate_allergen_codes_backward,
        ),
    ]
