# Generated by Django 5.2.4 on 2025-11-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_migrate_allergencode_to_allergen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergen',
            options={'ordering': ['kind', 'code']},
        ),
        migrations.AddField(
            model_name='allergen',
            name='kind',
            field=models.CharField(choices=[('ALLERGEN', 'Allergen'), ('ADDITIVE', 'Additive')], default='ALLERGEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='allergen',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
