# Generated by Django 5.2.4 on 2025-11-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_migrate_additives_to_allergens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='additives',
        ),
        migrations.DeleteModel(
            name='AdditiveLegend',
        ),
    ]
