# Generated by Django 5.2.4 on 2025-12-01 09:14

from django.db import migrations, models


def migrate_codes_forward(apps, schema_editor):
    """
    Migrate existing allergen codes into the new unified 'codes' field.
    Priority: manual_codes > generated_codes > extra_* > allergy_info
    """
    Dish = apps.get_model('core', 'Dish')
    
    updated_count = 0
    for dish in Dish.objects.all():
        codes_value = ""
        source_value = "generated"
        
        # Priority 1: Manual codes
        if dish.has_manual_codes and dish.manual_codes:
            codes_value = dish.manual_codes.strip()
            source_value = "manual"
        
        # Priority 2: Generated codes
        elif dish.generated_codes:
            codes_value = dish.generated_codes.strip()
            source_value = "generated"
        
        # Priority 3: Merge extra_allergens + extra_additives
        elif dish.extra_allergens or dish.extra_additives:
            # extra_allergens: ['A', 'G'] -> "A,G"
            letters = [str(c).strip().upper() for c in (dish.extra_allergens or []) if c]
            # extra_additives: [100, 200] -> "100,200"
            numbers = [str(n).strip() for n in (dish.extra_additives or []) if n]
            
            all_codes = letters + numbers
            if all_codes:
                codes_value = ",".join(all_codes)
                source_value = "manual"  # Assume manual if using extra_*
        
        # Priority 4: Legacy allergy_info
        elif dish.allergy_info:
            codes_value = dish.allergy_info.strip()
            source_value = "generated"
        
        # Update dish if we found codes
        if codes_value:
            dish.codes = codes_value
            dish.codes_source = source_value
            dish.save(update_fields=['codes', 'codes_source'])
            updated_count += 1
    
    print(f"✅ Migrated codes for {updated_count} dishes")


def migrate_codes_backward(apps, schema_editor):
    """
    Reverse migration: copy codes back to old fields
    """
    Dish = apps.get_model('core', 'Dish')
    
    for dish in Dish.objects.all():
        if not dish.codes:
            continue
            
        if dish.codes_source == 'manual':
            dish.manual_codes = dish.codes
            dish.has_manual_codes = True
        else:
            dish.generated_codes = dish.codes
            dish.has_manual_codes = False
        
        dish.save(update_fields=['manual_codes', 'generated_codes', 'has_manual_codes'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_additive_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='codes',
            field=models.CharField(blank=True, default='', help_text="Unified allergen & additive codes (e.g., 'A,G,200,300')", max_length=255),
        ),
        migrations.AddField(
            model_name='dish',
            name='codes_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('generated', 'Generated')], default='generated', help_text='Indicates whether codes were manually set or auto-generated', max_length=20),
        ),
        migrations.AlterField(
            model_name='dish',
            name='allergy_info',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='عناصر الحساسية (قديم - DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='extra_additives',
            field=models.JSONField(blank=True, default=list, editable=False, help_text="DEPRECATED: Merge into 'codes' instead"),
        ),
        migrations.AlterField(
            model_name='dish',
            name='extra_allergens',
            field=models.JSONField(blank=True, default=list, editable=False, help_text="DEPRECATED: Merge into 'codes' instead"),
        ),
        migrations.AlterField(
            model_name='dish',
            name='generated_codes',
            field=models.CharField(blank=True, default='', editable=False, help_text="DEPRECATED: Use 'codes' instead", max_length=255),
        ),
        migrations.AlterField(
            model_name='dish',
            name='has_manual_codes',
            field=models.BooleanField(default=False, editable=False, help_text="DEPRECATED: Use 'codes_source' instead"),
        ),
        migrations.AlterField(
            model_name='dish',
            name='manual_codes',
            field=models.CharField(blank=True, editable=False, help_text="DEPRECATED: Use 'codes' instead", max_length=255, null=True),
        ),
        
        # ✅ Data migration: populate codes from legacy fields
        migrations.RunPython(migrate_codes_forward, migrate_codes_backward),
    ]
