# Generated by Django 5.2.4 on 2025-12-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_dish_codes_dish_codes_source_alter_dish_allergy_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Optional public subtitle/description shown under the section name.', max_length=255),
        ),
    ]
