# Generated by Django 5.2.4 on 2025-12-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_extragroup_extra_dishextragroup_dish_extra_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='extra_groups',
        ),
        migrations.AddField(
            model_name='dish',
            name='extras',
            field=models.JSONField(blank=True, default=list, help_text='List of manual extras: [{name: str, price: decimal, sort_order: int}]'),
        ),
    ]
