# Generated by Django 5.2.4 on 2025-12-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_dish_extra_groups_dish_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudisplaysettings',
            name='social_facebook',
            field=models.CharField(blank=True, default='', help_text='Facebook profile URL', max_length=255),
        ),
        migrations.AddField(
            model_name='menudisplaysettings',
            name='social_instagram',
            field=models.CharField(blank=True, default='', help_text='Instagram profile URL', max_length=255),
        ),
        migrations.AddField(
            model_name='menudisplaysettings',
            name='social_tiktok',
            field=models.CharField(blank=True, default='', help_text='TikTok profile URL', max_length=255),
        ),
    ]
