# Generated by Django 5.2.4 on 2025-10-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllergenCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='المعرّف/الكود (قصير ومميّز) مثل: A1 أو GLUTEN.', max_length=32, unique=True)),
                ('name_de', models.CharField(blank=True, default='', help_text='الاسم بالألمانية (اختياري الآن).', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', help_text='الاسم بالإنجليزية (اختياري).', max_length=255)),
                ('name_ar', models.CharField(blank=True, default='', help_text='الاسم بالعربية (اختياري).', max_length=255)),
                ('notes', models.TextField(blank=True, default='', help_text='وصف/ملاحظات إضافية (اختياري).')),
                ('is_active', models.BooleanField(default=True, help_text='تفعيل/تعطيل الكود بدون حذفه.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
